### ISSUE TITLE
configuration file not passing through net::server options

### ISSUE THREAD

**Issue by corbolais** [munin-monitoring/munin#1175]
I'm trying to call a munin node from a master with dynamic IPs by adding

> allow ^dyndns-master\\.example\\.com$

which fails. Using the actual IP instead of a hostname is working.

`https://linux.die.net/man/5/munin-node.conf` states:

> The format is dictated by the use of "Net::Server". A look at "perldoc Net::Server" will give a list of options that the file supports by using the module.

and `https://github.com/munin-monitoring/munin/blob/master/doc/reference/munin-node.conf.rst` states:

> The directives "host_name", "paranoia" and "ignore_file" are munin node specific.
> 
> All other directives in munin-node.conf are passed through to the Perl module Net::Server. Depending on the version installed, you may have different settings available.

So, this should work:

> reverse_lookups 1
> allow allow ^dyndns-master\\.example\\.com$

But it does not work. The same goes for:

> conf_file "/etc/munin/munin-dynip.conf"

containing 

> allow ^11\.12\.13\.14$

Which is a fail, also.

Where's Wally? Is the documentation faulty, the implementation not according to doc or am I reading in something that isn't there?

Looking at the Config.pm it seems only a selected set of options is passed through to net::server. This should either get correctly documented or correctly implemented to spec, IMO.

Versions used: munin-*        2.0.47-1

**Comment by sumpfralle** [comment]
There are three issues involved here:
1. munin does not hand over the configuration key `reverse_lookups` to Net::Server
2. Net::Server fails to resolve the DNS name of the client, if the server is bound to an IPv6 socket (see [cpan#129377](https://rt.cpan.org/Ticket/Display.html?id=129377]))
3. Net::Server fails to check the result of the reverse DNS resolution properly (see [cpan#83909](https://rt.cpan.org/Public/Bug/Display.html?id=83909))

The munin issue is easy to solve.

The second issue needs a fix within `Net::Server`. Binding munin-node only to the IPv4 socket is a workaround for this issue.

The third issue needs to be addressed by `Net::Server`, too. This issue turns "reverse_lookups" into a convenience feature (instead of a safety check), since it allows an attacker to circumvent the check easily by assigning an arbitrary reverse DNS name to his IP address.

**Comment by sumpfralle** [comment]
Fixed in b53c6ecbe014bcd8c4edef6a538480dc64900e79.

The issues related to `Net::Server` remain open.

**Comment by corbolais** [comment]
@sumpfralle Thank you. :-)

Though, that Net::Server issue is still pressing.
