### ISSUE TITLE
cidr_allow breaks in dual-stack configurations

### ISSUE THREAD

**Issue by mpounsett** [munin-monitoring/munin#1177]
**Describe the bug**

`cidr_allow` breaks for the second protocol family used in the munin-node config.

If I list an IPv4 block first, and IPv6 second, then IPv4 connections work but IPv6 connections are refused and munin-node logs an error from Net::Server reporting a bad netblock (passed from Munin?).  If I list an IPv6 block first, IPv6 connections work but IPv4 connections fail and Net::Server reports a bad netblock.

In both cases, the string reported as a bad netblock by Net::Server looks vaguely like an IPv4 address with far too many quads and occasionally hyphens.

**To Reproduce**
1. Add both a v4 block and a v6 block in munin-node.conf using cidr_allow
2. attempt to connect with both v4 and v6
3. see one fail.

**Expected behavior**

I expect that in a dual-stack configuration, it should be possible to list v4 and v6 netblocks that are allowed to connect to munin-node.

**Screenshots & Logs**

v4 first:

```
% egrep '^(cidr_)?allow' /etc/munin/munin-node.conf
allow ^127\.0\.0\.1$
allow ^::1$
cidr_allow 64.191.0.0/24
cidr_allow 2620:ff:c000::/64
```

v4 connection followed by v6 connection:

```
2019/04/09-13:09:21 CONNECT TCP Peer: "[::ffff:64.191.0.6]:60226" Local: "[::ffff:64.191.0.81]:4949"
2019/04/09-13:09:24 CONNECT TCP Peer: "[2620:ff:c000::6]:35784" Local: "[2620:ff:c000::81]:4949"
Invalid netblock: 64.191.0.255-38.32.0.255.192.0.0.0.0.0.0.0.0.0.0.6 at /usr/share/perl5/Net/Server.pm line 601.
```

v6 first:

```
% egrep '^(cidr_)?allow' /etc/munin/munin-node.conf
allow ^127\.0\.0\.1$
allow ^::1$
cidr_allow 2620:ff:c000::/64
cidr_allow 64.191.0.0/24
```

v4 connection followed by v6 connection:

```
2019/04/09-13:10:48 CONNECT TCP Peer: "[::ffff:64.191.0.6]:32790" Local: "[::ffff:64.191.0.81]:4949"
Invalid netblock: 38.32.0.255.192.0.0.0.255.255.255.255.255.255.255.255-64.191.0.6 at /usr/share/perl5/Net/Server.pm line 601.
2019/04/09-13:10:50 CONNECT TCP Peer: "[2620:ff:c000::6]:36590" Local: "[2620:ff:c000::81]:4949"
```

**Desktop (please complete the following information):**
 - OS+Distribution Version: Devuan GNU/Linux 1 (jessie) [Debian]
 - Munin Version v2.0.25-1+deb8u3

**Comment by orzel** [comment]
I can confirm this

**Comment by neirbowj** [comment]
Resolved by svarshavchik/Net-CIDR#1 and released in [Net::CIDR 0.20](https://metacpan.org/release/MRSAM/Net-CIDR-0.20).

**Comment by sumpfralle** [comment]
@neirbowj: great - thank you for pointing this out!

@mpounsett: please re-open this issue, if the new release of Net::CIDR does not solve the problem for you.
